// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYbyrwdDzVwEDirJ7c48_6dfQAWa-gppk',
    appId: '1:62340599934:web:3f3049f044f7d6657d482f',
    messagingSenderId: '62340599934',
    projectId: 'hobi-hub-app',
    authDomain: 'hobi-hub-app.firebaseapp.com',
    storageBucket: 'hobi-hub-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDDJ8cXqH3sTC1QOguP6660TqMRgq49Uc',
    appId: '1:62340599934:android:8947a455e385bd877d482f',
    messagingSenderId: '62340599934',
    projectId: 'hobi-hub-app',
    storageBucket: 'hobi-hub-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy_SgYR1wVqqJdS5Xp6GTjQwH9c45hFyo',
    appId: '1:62340599934:ios:b49f74e34bd05e2d7d482f',
    messagingSenderId: '62340599934',
    projectId: 'hobi-hub-app',
    storageBucket: 'hobi-hub-app.appspot.com',
    iosBundleId: 'com.example.hobihub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy_SgYR1wVqqJdS5Xp6GTjQwH9c45hFyo',
    appId: '1:62340599934:ios:00c8c1e6b37137f17d482f',
    messagingSenderId: '62340599934',
    projectId: 'hobi-hub-app',
    storageBucket: 'hobi-hub-app.appspot.com',
    iosBundleId: 'com.example.hobihub.RunnerTests',
  );
}
