// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP74AXcs_fHtT3VS4Yx2WuSt84eLSGJxY',
    appId: '1:336002918720:web:83a0d31e1b69c60d14f2a5',
    messagingSenderId: '336002918720',
    projectId: 'hobihub',
    authDomain: 'hobihub.firebaseapp.com',
    storageBucket: 'hobihub.appspot.com',
    measurementId: 'G-FCP23490KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxu8M5lexwXCKvVv36Sx7OaHRa40-NkFY',
    appId: '1:336002918720:android:9d95084d807ee1dc14f2a5',
    messagingSenderId: '336002918720',
    projectId: 'hobihub',
    storageBucket: 'hobihub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFg4KkDKOVVY-oHW5A4yuksfSmXo64uW8',
    appId: '1:336002918720:ios:f7f3de17dcb7041014f2a5',
    messagingSenderId: '336002918720',
    projectId: 'hobihub',
    storageBucket: 'hobihub.appspot.com',
    iosBundleId: 'com.example.hobihub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFg4KkDKOVVY-oHW5A4yuksfSmXo64uW8',
    appId: '1:336002918720:ios:d64a7704773faf0d14f2a5',
    messagingSenderId: '336002918720',
    projectId: 'hobihub',
    storageBucket: 'hobihub.appspot.com',
    iosBundleId: 'com.example.hobihub.RunnerTests',
  );
}
